application: php-p3-1211
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
  
- url: /
  script: /main.php
  
- url: /busreis
  script: /busreis.php

- url: /project
  script: /project.php

- url: /kerstboom
  script: /kerstboom.php
  
- url: /zwemclub
  script: /zwemclub.php
  
- url: /kapperzaak
  script: /kapperzaak.php
  
- url: /tafel1
  script: /tafel1.php

- url: /functions
  script: /functions.php

- url: /projectlogin
  script: /projectlogin.php

- url: /includes/nav/nav.php
  script: /includes/nav/nav.php
  
- url: /webshop
  script: /webshop.php
  
- url: /dynamicwebsite
  script: /dynamicwebsite.php
  
  